### ISSUE TITLE
can not supported react v16.

### ISSUE THREAD

**Issue by qqt2018** [aboeglin/react-router-v4-transition#13]
can not supported react v16.

**Comment by aboeglin** [comment]
@qqt2018 Can you be more specific and say what exactly does not work ? Is there any error in the console ?

**Comment by lorenzomigliorero** [comment]
`prevContext` argument isn't supported in React 16.

**Comment by eleventhirtyfour** [comment]
yep got the same problem

**Comment by aboeglin** [comment]
#18 fixes it and will be published to the npm package today !
