### ISSUE TITLE
Props not available in component

### ISSUE THREAD

**Issue by glenndehaan** [aboeglin/react-router-v4-transition#9]
After using the `<TransitionSwitch parallel={false}>` instead of `<Switch>` the props from the router are not available anymore in the component. Below my implementation:
```
<Router history={history}>
            <div>
                <Header />
                <div className="container">
                    <TransitionSwitch parallel={false}>
                        <Route exact path="/" component={Index}/>
                        <Route exact path="/projects" component={Projects}/>
                        <Route exact path="/project/:path" component={Project}/>
                        <Route exact path="/programming" component={Programming}/>
                        <Route exact path="/about" component={About}/>
                        <Route path="notfound" component={NotFound}/>
                        <Route path="*" component={NotFound}/>
                    </TransitionSwitch>
                </div>
            </div>
        </Router>
```

**Comment by milesaylward** [comment]
Having same issue can no longer programmatically navigate

**Comment by ray-su** [comment]
Having the same issues here,  after switching from `<Swtich>` to `<TransitionSwitch>` it gives me "TypeError: Cannot read property 'path' of undefined"

**Comment by sylvainbaronnet** [comment]
I've fixed it in https://github.com/aboeglin/react-router-v4-transition/pull/10

You can use https://github.com/sylvainbaronnet/react-router-v4-transition until it's merged

**Comment by aboeglin** [comment]
I was on holidays, I should have time to fix it in about a week when I'm fully back. But I believe #10 isn't enough for the issue of @ray201314. If you look here https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js, line 59 the original Switch passes the location and computedMatch to the matching child. I guess the error comes from an access to location.path which doesn't exist. In the render method we need to pass these along.

If anyone has time in the coming days, feel free to provide a PR with a test.
